services:
    server1:
        build: 
            context: server
            args:
                DATABASE_HOST: database
                DATABASE_NAME: chobots
                DATABASE_USER: root
                DATABASE_PASSWORD: root
        environment:
            - KAVALOK_SECRET_KEY=${KAVALOK_SECRET_KEY}
            - KAVALOK_SERVER_ID=1
        ports:
           - 8935:1935
           - 5080:5080
        depends_on:
            database:
                condition: service_healthy
    server2:
        build:
            context: server
            args:
                DATABASE_HOST: database
                DATABASE_NAME: chobots
                DATABASE_USER: root
                DATABASE_PASSWORD: root
        environment:
            - KAVALOK_SECRET_KEY=${KAVALOK_SECRET_KEY}
            - KAVALOK_SERVER_ID=2
        ports:
            - 8936:1935
        depends_on:
            database:
                condition: service_healthy
    client:
        build: 
            context: client
            args:
                RTMP_USE_TLS: false
                RTMP_HOSTNAME: localhost
                RTMP_PORT: 8935
        ports:
            - 8080:80
        volumes:
            - ./client/website:/usr/share/nginx/html
    database:
        build: database
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: chobots
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        command: [
            "mariadbd",
            "--log-bin=mysql-bin",
            "--server-id=1",
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_unicode_ci",
            "--sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION",
            "--bind-address=0.0.0.0",
            "--wait-timeout=28800",
            "--interactive-timeout=28800",
            "--max-connections=200",
            "--connect-timeout=60",
            "--net-read-timeout=60",
            "--net-write-timeout=60"
        ]
        healthcheck:
            test: [ "CMD-SHELL", "mariadb-admin ping -uroot -proot --silent" ]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - 3307:3306
        volumes:
            - database:/var/lib/mysql

volumes:
    database: